# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:android)

platform :android do
  # =================================================
  # ============== QA Lane (Debug) ==================
  # =================================================
  desc "Build and deploy a new debug build to Firebase App Distribution"
  lane :qa do
    # Gradle을 사용해 Debug APK를 빌드합니다.
    gradle(
      task: "clean assembleDebug"
    )

    # Firebase App Distribution에 업로드합니다.
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_DEBUG"], # .debug용 앱 ID
      service_credentials_file: ENV["FIREBASE_SERVICE_CREDENTIALS_JSON_PATH"],
      groups: "qa-team",
      release_notes: "Git 마지막 커밋 메시지: #{last_git_commit[:message]}"
    )
  end

  # =================================================
  # ========= Production Lane (Release) =============
  # =================================================
  desc "Upload Release AAB to Google Play Store (Production Track)"
  lane :upload_production do
    # Fastlane은 오직 '업로드' 역할만 수행합니다.

    upload_to_play_store(
      track: 'production',
      release_status: 'draft',
      package_name: 'com.hilingual',
      aab: ENV['PLAY_STORE_AAB_FILE'],
      json_key: ENV['PLAY_STORE_JSON_KEY_FILE'],
      skip_upload_screenshots: true,
      skip_upload_images: true,
      metadata_path: 'fastlane/metadata/android'
    )
  end
end
