name: Update Module Dependency Graph

on:
  push:
    branches:
      - develop
    paths:
      - '**/build.gradle.kts'

jobs:
  update-graph:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create local.properties from secret
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: |
          echo "${LOCAL_PROPERTIES}" > local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> local.properties

      - name: Generate project dependency graph
        run: ./gradlew projectDependencyGraph

      - name: Copy graph image to project root
        run: cp build/reports/dependency-graph/project.dot.png project-dependency-graph.png

      - name: Update README.md with graph
        shell: bash
        run: |
          README_PATH="README.md"
          GRAPH_IMAGE_PATH="project-dependency-graph.png"
          START_MARKER="<!--- MODULE_DEPENDENCY_GRAPH_START -->"
          END_MARKER="<!--- MODULE_DEPENDENCY_GRAPH_END -->"
          IMAGE_MARKDOWN="![Module Dependency Graph](${GRAPH_IMAGE_PATH})"

          if grep -q "$START_MARKER" "$README_PATH" && grep -q "$END_MARKER" "$README_PATH"; then
            awk -v s="$START_MARKER" -v e="$END_MARKER" -v img="$IMAGE_MARKDOWN" '
              BEGIN { inBlock=0 }
              $0 ~ s { print s; print img; print e; inBlock=1; next }
              $0 ~ e { inBlock=0; next }
              !inBlock { print }
            ' "$README_PATH" > tmp && mv tmp "$README_PATH"
            echo "README.md updated successfully."
          else
            echo -e "\n\n$START_MARKER\n$IMAGE_MARKDOWN\n$END_MARKER" >> "$README_PATH"
            echo "Markers not found. Appended to README.md."
          fi

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(readme): Update module dependency graph"
          branch: develop
          file_pattern: |
            README.md
            project-dependency-graph.png
